### ISSUE TITLE
ServerSocket only has a port option

### ISSUE THREAD

**Issue by JayArrowz** [ultraviolet-jordan/xlite2#4]
https://github.com/ultraviolet-jordan/xlite2/blob/4ff784b2363c6382f417dfbda6006dd27402d252/socket/src/main/kotlin/com/xlite/socket/ServerSocket.kt#L7

What if someone wanted to set their NIC bind address specifically.
Use InetSocketAddress in this class?

**Comment by ultraviolet-jordan** [comment]
This class no longer exists in the upcoming feature branch.

Hostnames are set inside the jav_config properties file.
